import type { Metadata } from "next"
import { Geist } from "next/font/google"
import "./globals.css"
import Navbar from "@/modules/navbar/Navbar"
import { Toaster } from "react-hot-toast"
import { QueryProvider } from "@/providers/QueryProvider"
const geist = Geist({
	variable: "--font-sans",
	subsets: ["latin"],
	display: "swap",
})

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body className={`${geist.className} antialiased`}>
				<QueryProvider>
					<Toaster
						position="top-right"
						reverseOrder={false}
						toastOptions={{
							style: {
								backgroundColor: "var(--primary-container)",
								color: "var(--on-primary-container)",
								borderRadius: "var(--radius)",
							},
							success: {
								style: {
									backgroundColor: "var(--success)",
									color: "var(--on-success)",
								},
							},
							error: {
								style: {
									backgroundColor: "var(--error)",
									color: "var(--on-tertiary)",
								},
							},
						}}
					/>
					<Navbar />
					{children}
				</QueryProvider>
			</body>
		</html>
	)
}
